# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: McKinney Party of 5
author: Patrick & Kara McKinney
email: mckinneypartyof5blog@gmail.com
description: We write blogs on all kinds of topics. From the adventures we take, to the things we are digging right now. From challenges we choose to take on, to the struggles we cannot control. We hope you find inspiration, camaraderie or just some laughs along the way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mckinneypartyof5.life/" # the base hostname & protocol for your site
permalink: /:year/:month/:title
development: true

# Build settings
markdown: kramdown
