# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: McKinney Party of Five
author: Patrick & Kara McKinney
email: your-email@domain.com
description: We need to update this.
baseurl: "/mckinney-blog" # the subpath of your site, e.g. /blog
url: "https://pnmcartodesign.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
